languageCode = "en-us"
title = "Shitty Christians | A Comedy Podcast About the Evils of Capitalism and Kirk Cameron"
baseURL = "https://alextaber.github.io/"
theme = "hugo-theme-massively"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

enableRobotsTXT = true
canonifyURLs = true

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"

# Below parameters can be set to override default post settings
# [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = true
#     paginationPages = 2
#     showFirstLast = false
 
[languages]
[languages.en]
  languageName = "English"
[languages.es]
  languageName = "Español"
  title = "Massively - Versión Español"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"